"""Testes das migrações do Alembic (precisam de banco).

1. O esquema criado pelas migrações é IGUAL ao descrito pelos modelos (app/models.py).
   Se alguém mudar um modelo e esquecer de gerar a migração, este teste falha.
2. Todas as migrações sobem e descem sem erro (o downgrade também precisa funcionar).
"""

from alembic import command
from sqlalchemy import Engine, inspect

from tests.conftest import alembic_config


def test_modelos_e_migracoes_estao_sincronizados(db_engine: Engine):
    with db_engine.connect() as connection:
        # Levanta AutogenerateDiffsDetected se houver diferença entre modelos e banco.
        command.check(alembic_config(connection))


def test_migracoes_descem_e_sobem(db_engine: Engine):
    # No PostgreSQL, até CREATE/DROP TABLE respeitam transações ("DDL transacional"):
    # fazemos tudo dentro de uma e desfazemos no fim, sem afetar os outros testes.
    with db_engine.connect() as connection:
        transaction = connection.begin()
        config = alembic_config(connection)

        command.downgrade(config, "base")
        assert inspect(connection).get_table_names() == ["alembic_version"]

        command.upgrade(config, "head")
        assert "prefix_cache" in inspect(connection).get_table_names()

        transaction.rollback()
