"""create prefix_cache

Cria a tabela do cache de faixas do HIBP (fase 3). Gerada com --autogenerate e revisada.

Revision ID: 0001
Revises:
Create Date: 2026-09-29 00:52:14.877159
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Identificadores usados pelo Alembic para montar a corrente de migrações.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica a migração (avança o esquema)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prefix_cache",
        sa.Column("prefix", sa.String(length=5), nullable=False),
        sa.Column("suffixes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("prefix ~ '^[0-9A-F]{5}$'", name=op.f("ck_prefix_cache_prefix_hex")),
        sa.PrimaryKeyConstraint("prefix", name=op.f("pk_prefix_cache")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Desfaz a migração (volta o esquema ao estado anterior)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prefix_cache")
    # ### end Alembic commands ###
