"""create rate_limit_counters and usage_metrics

Contadores do rate limit e métricas de uso por dia (fase 5). Gerada com --autogenerate e revisada.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 01:26:30.055875
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Identificadores usados pelo Alembic para montar a corrente de migrações.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica a migração (avança o esquema)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_counters",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("key", "window_start", name=op.f("pk_rate_limit_counters")),
    )
    op.create_table(
        "usage_metrics",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("checks", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("policies", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("ranges", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("breached", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_hits", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_misses", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_stale", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("registrations", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rate_limited", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_metrics")),
        sa.UniqueConstraint("day", name=op.f("uq_usage_metrics_day")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Desfaz a migração (volta o esquema ao estado anterior)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage_metrics")
    op.drop_table("rate_limit_counters")
    # ### end Alembic commands ###
